# Generated by Django 5.2.1 on 2025-06-02 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myusers',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='username',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myusers',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
